import {
  Stethoscope,
  Scale,
  Building2,
  Hammer,
  Calculator,
  Factory,
  Briefcase,
  Home as HomeIcon,
  ShoppingCart,
  Heart,
  Wrench,
  Smile,
  type LucideIcon,
} from "lucide-react";

export type IndustryEntry = {
  slug: string;
  icon: LucideIcon;
  name: string;
  tagline: string;
  intro: string;
  challenges: string[];
  solutions: string[];
  metaTitle: string;
  metaDesc: string;
};

export const INDUSTRIES: IndustryEntry[] = [
  {
    slug: "healthcare",
    icon: Stethoscope,
    name: "Healthcare",
    tagline: "HIPAA-aware websites for clinics, hospitals, and providers.",
    intro: "We build secure, accessible, conversion-focused websites for healthcare providers across USA & Canada — with HIPAA-aware workflows, patient-portal integrations, and content built to earn trust.",
    challenges: ["HIPAA and PIPEDA compliance pressure", "Outdated, slow patient-facing sites", "Disconnected booking, EHR, and forms", "Local SEO competition from directories"],
    solutions: ["Secure, accessibility-audited builds", "Booking + EHR + telehealth integrations", "Local SEO for every service location", "24/7 monitoring and care plans"],
    metaTitle: "Healthcare Website Development & SEO | WebCentauri",
    metaDesc: "HIPAA-aware websites, SEO, and support for clinics, hospitals, and providers across USA & Canada.",
  },
  {
    slug: "dental",
    icon: Smile,
    name: "Dental",
    tagline: "Booking-optimized dental practice websites.",
    intro: "Conversion-focused dental websites with strong local SEO, online booking, and clear pricing — built to fill the schedule, not just look modern.",
    challenges: ["Empty appointment slots", "Weak Google Business presence", "Slow, hard-to-update sites"],
    solutions: ["Booking + reminders + reviews flow", "Local SEO and map pack optimization", "Fast, easy-to-update WordPress builds"],
    metaTitle: "Dental Website Design & Local SEO | WebCentauri",
    metaDesc: "Booking-optimized dental websites with strong local SEO across USA & Canada.",
  },
  {
    slug: "legal",
    icon: Scale,
    name: "Legal",
    tagline: "Authoritative law firm websites that win cases.",
    intro: "Practice-area-deep websites for law firms — built on legal-grade content, ethics compliance, and a steady stream of qualified consultations.",
    challenges: ["Crowded paid-search market", "Generic, undifferentiated content", "Slow intake and form follow-up"],
    solutions: ["Practice-area content depth", "Conversion-focused intake design", "Local + content SEO + paid attribution"],
    metaTitle: "Law Firm Website Development & SEO | WebCentauri",
    metaDesc: "Authoritative websites, SEO, and growth for law firms across USA & Canada.",
  },
  {
    slug: "real-estate",
    icon: HomeIcon,
    name: "Real Estate",
    tagline: "IDX-ready sites for agents and brokerages.",
    intro: "IDX-integrated, search-optimized websites for agents, teams, and brokerages — designed to capture leads and nurture them automatically.",
    challenges: ["IDX/MLS integration limits", "Slow, image-heavy pages", "Lead leakage to portals"],
    solutions: ["Fast IDX search + saved alerts", "Neighborhood and listing SEO", "CRM + nurture automation"],
    metaTitle: "Real Estate Website Development | WebCentauri",
    metaDesc: "IDX-ready, SEO-optimized websites for real estate agents, teams, and brokerages.",
  },
  {
    slug: "construction",
    icon: Hammer,
    name: "Construction",
    tagline: "Portfolio-driven sites for contractors and builders.",
    intro: "Project-portfolio websites for general contractors, custom home builders, and commercial firms — built to win bigger bids.",
    challenges: ["Outdated portfolio presentation", "Slow estimate-request flow", "Weak rankings vs. national firms"],
    solutions: ["Visual project showcases", "Estimate intake + qualification", "Local + service-area SEO"],
    metaTitle: "Construction & Contractor Website Development | WebCentauri",
    metaDesc: "Portfolio-driven websites and SEO for contractors, builders, and construction firms.",
  },
  {
    slug: "home-services",
    icon: Wrench,
    name: "Home Services",
    tagline: "Lead-gen sites for plumbers, HVAC, electricians.",
    intro: "Mobile-first home services websites with click-to-call, service-area SEO, and review flows — engineered to dominate the local market.",
    challenges: ["Mobile-first, fast-conversion needs", "Service-area SEO complexity", "Review and reputation management"],
    solutions: ["Click-to-call + booking forms", "Service-area landing pages", "Reviews + Google Business automation"],
    metaTitle: "Home Services Website & Lead Gen | WebCentauri",
    metaDesc: "Mobile-first websites and local SEO for plumbers, HVAC, electricians, and home services pros.",
  },
  {
    slug: "finance",
    icon: Building2,
    name: "Finance",
    tagline: "Compliant, trustworthy sites for advisors & firms.",
    intro: "Compliance-ready websites for financial advisors, wealth managers, and fintech — calm, credible, and built to convert qualified leads.",
    challenges: ["Compliance and disclosure review", "Trust-building above the fold", "Lead quality over lead volume"],
    solutions: ["Compliance-friendly CMS workflows", "Authority-led content design", "Qualified-lead intake forms"],
    metaTitle: "Financial Services Website Development | WebCentauri",
    metaDesc: "Compliant, trust-first websites for advisors, wealth managers, and fintech across USA & Canada.",
  },
  {
    slug: "accounting",
    icon: Calculator,
    name: "Accounting",
    tagline: "Client-portal-ready websites for CPAs.",
    intro: "Modern accounting and CPA firm websites with client portals, secure file exchange, and content that ranks for tax-season demand.",
    challenges: ["Seasonal demand spikes", "Secure document exchange", "Standing out from chain firms"],
    solutions: ["Portal + secure intake", "Niche service-line content", "Local SEO and reviews"],
    metaTitle: "Accounting & CPA Website Development | WebCentauri",
    metaDesc: "Client-portal-ready websites and SEO for CPAs, bookkeepers, and accounting firms.",
  },
  {
    slug: "manufacturing",
    icon: Factory,
    name: "Manufacturing",
    tagline: "B2B websites with deep product & capability content.",
    intro: "Industrial and B2B manufacturer websites with deep product catalogs, capability content, and SEO that earns RFQs from the right buyers.",
    challenges: ["Complex product catalogs", "Long, multi-stakeholder sales cycles", "Thin or outdated SEO"],
    solutions: ["Catalog + spec-sheet architecture", "Capabilities-led storytelling", "Technical and category SEO"],
    metaTitle: "Manufacturing Website Development | WebCentauri",
    metaDesc: "B2B websites, catalogs, and SEO for industrial manufacturers across USA & Canada.",
  },
  {
    slug: "ecommerce",
    icon: ShoppingCart,
    name: "eCommerce",
    tagline: "Shopify & WooCommerce stores built to scale.",
    intro: "Stores designed for conversion and built for scale — from first-launch DTC brands to enterprise replatforms.",
    challenges: ["Checkout friction and abandonment", "Slow storefronts hurting SEO", "Disconnected ops and marketing stack"],
    solutions: ["Conversion-focused checkout work", "Headless or hybrid storefronts", "CRM, ESP, and ERP integrations"],
    metaTitle: "eCommerce Development — Shopify, WooCommerce | WebCentauri",
    metaDesc: "Conversion-focused Shopify and WooCommerce stores, CRO, and ongoing support.",
  },
  {
    slug: "professional-services",
    icon: Briefcase,
    name: "Professional Services",
    tagline: "Lead-gen sites for agencies, consultants, coaches.",
    intro: "Authority-led websites for agencies, consultants, and B2B service firms — designed to position you as the obvious choice.",
    challenges: ["Generic, look-alike positioning", "Weak case-study storytelling", "Inconsistent lead flow"],
    solutions: ["Differentiated positioning + design", "Case studies that sell", "Inbound + outbound funnel build-out"],
    metaTitle: "Agency & Consulting Website Development | WebCentauri",
    metaDesc: "Positioning-led websites and growth programs for agencies, consultants, and B2B service firms.",
  },
  {
    slug: "nonprofits",
    icon: Heart,
    name: "Nonprofits",
    tagline: "Donation-ready sites for mission-driven orgs.",
    intro: "Mission-first websites with donation flows, volunteer signups, and storytelling that turns visitors into supporters.",
    challenges: ["Donation friction", "Volunteer + program management", "Limited internal tech capacity"],
    solutions: ["Donation + recurring giving flows", "Volunteer and program signups", "Care plans built for lean teams"],
    metaTitle: "Nonprofit Website Development & Support | WebCentauri",
    metaDesc: "Donation-ready websites, SEO, and ongoing support for mission-driven nonprofits.",
  },
];