import {
  Stethoscope, Scale, Building2, Hammer, Calculator, Factory, Briefcase,
  Home as HomeIcon, ShoppingCart, Heart, Wrench, Smile, GraduationCap,
  Utensils, Plane, Car, Dumbbell, Scissors, Camera, Music, Film, Palette,
  Hotel, Truck, Ship, Train, Fuel, Leaf, TreePine, Sprout, Wheat, Fish,
  Pill, Microscope, FlaskConical, Brain, Baby, Dog, Church, Landmark,
  ShieldCheck, Gavel, BookOpen, Library, School, Trophy, Gamepad2, Tv,
  Newspaper, Radio, Mic, Coffee, Pizza, Wine, Beer, Cookie, Store, Tag,
  Shirt, Gem, Watch, Sparkles, Bath, Sofa, Bed, Lightbulb, Zap, Battery,
  Cloud, Server, Cpu, Database, Code, Smartphone, Wifi, Satellite, Rocket,
  Banknote, CreditCard, Coins, TrendingUp, PiggyBank, Receipt, Building,
  Warehouse, Package, Boxes, Forklift, HardHat, Drill, Paintbrush, Ruler,
  Mountain, Tent, Bike, Sailboat, Anchor, Compass, Globe, Users, HandHeart,
  type LucideIcon,
} from "lucide-react";

export type IndustryEntry = {
  slug: string;
  icon: LucideIcon;
  name: string;
  category: string;
  tagline: string;
  intro: string;
  challenges: string[];
  solutions: string[];
  metaTitle: string;
  metaDesc: string;
};

const mk = (
  slug: string, icon: LucideIcon, name: string, category: string, tagline: string,
  intro: string, challenges: string[], solutions: string[]
): IndustryEntry => ({
  slug, icon, name, category, tagline, intro, challenges, solutions,
  metaTitle: `${name} Website Development & SEO | WebCentauri`,
  metaDesc: `${tagline} Web, SEO, and ongoing support for ${name.toLowerCase()} businesses across USA & Canada.`,
});

export const INDUSTRIES: IndustryEntry[] = [
  // Healthcare & Wellness
  mk("healthcare", Stethoscope, "Healthcare", "Healthcare & Wellness", "HIPAA-aware websites for clinics, hospitals, and providers.",
    "Secure, accessible, conversion-focused websites for healthcare providers — with HIPAA-aware workflows, patient-portal integrations, and content built to earn trust.",
    ["HIPAA and PIPEDA compliance pressure", "Outdated, slow patient-facing sites", "Disconnected booking, EHR, and forms", "Local SEO competition from directories"],
    ["Secure, accessibility-audited builds", "Booking + EHR + telehealth integrations", "Local SEO for every service location", "24/7 monitoring and care plans"]),
  mk("dental", Smile, "Dental", "Healthcare & Wellness", "Booking-optimized dental practice websites.",
    "Conversion-focused dental websites with strong local SEO, online booking, and clear pricing — built to fill the schedule.",
    ["Empty appointment slots", "Weak Google Business presence", "Slow, hard-to-update sites"],
    ["Booking + reminders + reviews flow", "Local SEO and map pack optimization", "Fast, easy-to-update WordPress builds"]),
  mk("mental-health", Brain, "Mental Health & Therapy", "Healthcare & Wellness", "Calm, trust-first sites for therapists & counselors.",
    "Warm, compliant websites for therapists, counselors, and behavioral health practices — designed to lower the barrier to that first call.",
    ["Stigma and trust barriers", "Insurance and intake friction", "HIPAA-compliant intake forms"],
    ["Empathy-led messaging and design", "Secure intake + scheduling", "Local SEO for every specialty"]),
  mk("pharmacy", Pill, "Pharmacy", "Healthcare & Wellness", "Modern pharmacy and compounding websites.",
    "eCommerce-ready pharmacy websites with refill flows, compliance content, and local SEO.",
    ["Prescription refill workflows", "Compliance and labeling", "Competition from chains"],
    ["Refill + transfer flows", "Compliance-aware CMS", "Hyper-local SEO"]),
  mk("medical-labs", Microscope, "Medical Labs & Diagnostics", "Healthcare & Wellness", "B2B sites for labs and diagnostics providers.",
    "Authoritative websites for diagnostic labs, imaging centers, and clinical research — built for referrals and partnerships.",
    ["Referrer trust and education", "Complex test catalogs", "B2B and B2C audiences in one site"],
    ["Test catalog architecture", "Referrer portals", "Education-led content SEO"]),
  mk("veterinary", Dog, "Veterinary Clinics", "Healthcare & Wellness", "Booking sites for vets and animal hospitals.",
    "Friendly, fast veterinary websites with booking, reminders, and emergency-care messaging.",
    ["Emergency vs. routine intake", "Multi-doctor scheduling", "Pet owner education"],
    ["Booking + reminder flows", "Service-line content", "Local SEO + reviews"]),
  mk("pediatrics", Baby, "Pediatrics & Family Care", "Healthcare & Wellness", "Trust-first pediatric and family practice sites.",
    "Warm, parent-friendly websites for pediatricians and family practices with portal-ready intake and education libraries.",
    ["Parent trust and reassurance", "After-hours guidance", "Insurance complexity"],
    ["Parent-focused messaging", "Triage and education content", "Portal integrations"]),
  mk("fitness", Dumbbell, "Fitness & Gyms", "Healthcare & Wellness", "Membership-driving websites for gyms and studios.",
    "Conversion-focused websites for gyms, yoga studios, CrossFit boxes, and personal trainers — with class booking and membership flows.",
    ["Class booking and waitlists", "Membership churn", "Trial-to-paid conversion"],
    ["Class booking + memberships", "Trial offer landing pages", "Email + SMS automation"]),
  mk("spa-beauty", Sparkles, "Spa, Beauty & Salons", "Healthcare & Wellness", "Booking-first sites for spas and salons.",
    "Elegant, mobile-first websites for spas, salons, med-spas, and beauty studios — designed around booking and gift cards.",
    ["Mobile booking friction", "Stylist-level scheduling", "Gift card and package sales"],
    ["Mobile-first booking flows", "Service menus + packages", "Reviews and Instagram integration"]),

  // Legal & Professional Services
  mk("legal", Scale, "Law Firms", "Legal & Professional", "Authoritative law firm websites that win cases.",
    "Practice-area-deep websites for law firms — built on legal-grade content, ethics compliance, and qualified consultations.",
    ["Crowded paid-search market", "Generic, undifferentiated content", "Slow intake and form follow-up"],
    ["Practice-area content depth", "Conversion-focused intake design", "Local + content SEO + paid attribution"]),
  mk("accounting", Calculator, "Accounting & CPAs", "Legal & Professional", "Client-portal-ready websites for CPAs.",
    "Modern accounting and CPA firm websites with client portals, secure file exchange, and tax-season-ready content.",
    ["Seasonal demand spikes", "Secure document exchange", "Standing out from chain firms"],
    ["Portal + secure intake", "Niche service-line content", "Local SEO and reviews"]),
  mk("consulting", Briefcase, "Consulting Firms", "Legal & Professional", "Authority-led sites for consultants.",
    "Positioning-led websites for management, IT, and boutique consulting firms — built to attract enterprise buyers.",
    ["Generic positioning", "Long sales cycles", "Thought-leadership distribution"],
    ["Sharp positioning + design", "Case studies that sell", "Content + LinkedIn distribution"]),
  mk("insurance", ShieldCheck, "Insurance Agencies", "Legal & Professional", "Quote-driving sites for agencies & brokers.",
    "Conversion-optimized websites for independent agencies, brokers, and MGAs — with quote forms and carrier integrations.",
    ["Quote form abandonment", "Carrier comparison content", "Local trust building"],
    ["Streamlined quote flows", "Coverage-focused content", "Local SEO + reviews"]),
  mk("staffing", Users, "Staffing & Recruiting", "Legal & Professional", "Two-sided sites for staffing firms.",
    "Two-sided websites for staffing, recruiting, and executive search — built for both candidates and employers.",
    ["Two-audience navigation", "Job board integrations", "Employer brand storytelling"],
    ["Dual-funnel architecture", "ATS + job board sync", "Employer + candidate content"]),
  mk("notary", Gavel, "Notary & Legal Services", "Legal & Professional", "Local-first sites for notaries and paralegals.",
    "Mobile-first websites for notaries, mobile signing agents, and paralegal services with strong local SEO.",
    ["Hyper-local competition", "Mobile booking", "Service area coverage"],
    ["Service-area landing pages", "Mobile booking forms", "Reviews + GBP optimization"]),

  // Real Estate & Property
  mk("real-estate", HomeIcon, "Real Estate Agents", "Real Estate & Property", "IDX-ready sites for agents and brokerages.",
    "IDX-integrated, search-optimized websites for agents, teams, and brokerages — designed to capture leads and nurture them.",
    ["IDX/MLS integration limits", "Slow, image-heavy pages", "Lead leakage to portals"],
    ["Fast IDX search + saved alerts", "Neighborhood and listing SEO", "CRM + nurture automation"]),
  mk("property-management", Building, "Property Management", "Real Estate & Property", "Tenant and owner portal websites.",
    "Property management websites with tenant portals, owner reporting, and lead-gen for new doors.",
    ["Tenant and owner portals", "Listing syndication", "Owner-acquisition content"],
    ["Portal integrations", "Listing feeds", "Owner-focused SEO"]),
  mk("mortgage", Banknote, "Mortgage & Lending", "Real Estate & Property", "Application-driving sites for lenders.",
    "Compliance-aware mortgage and lending websites with calculators, application flows, and LO-level pages.",
    ["Compliance and disclosures", "Application abandonment", "LO and branch pages"],
    ["Compliant CMS + calculators", "Streamlined application flow", "LO microsites"]),
  mk("construction", Hammer, "Construction & Contractors", "Real Estate & Property", "Portfolio-driven sites for builders.",
    "Project-portfolio websites for general contractors, custom home builders, and commercial firms — built to win bigger bids.",
    ["Outdated portfolio presentation", "Slow estimate-request flow", "Weak rankings vs. national firms"],
    ["Visual project showcases", "Estimate intake + qualification", "Local + service-area SEO"]),
  mk("architecture", Ruler, "Architecture & Design", "Real Estate & Property", "Portfolio sites for architects and designers.",
    "Beautifully art-directed websites for architecture, interior design, and landscape firms — designed to land the dream client.",
    ["Portfolio storytelling", "Slow image-heavy pages", "Award-and-press credibility"],
    ["Custom case study layouts", "Image-optimized builds", "Press and awards modules"]),
  mk("interior-design", Sofa, "Interior Design", "Real Estate & Property", "Visual portfolios for interior designers.",
    "Editorial-quality websites for interior designers and staging firms — with mood boards, portfolios, and inquiry flows.",
    ["Heavy image performance", "Project storytelling", "Premium positioning"],
    ["Optimized image pipelines", "Project case studies", "Editorial design systems"]),

  // Home Services & Trades
  mk("home-services", Wrench, "Home Services (General)", "Home Services & Trades", "Lead-gen sites for plumbers, HVAC, electricians.",
    "Mobile-first home services websites with click-to-call, service-area SEO, and review flows.",
    ["Mobile-first, fast-conversion needs", "Service-area SEO complexity", "Review and reputation management"],
    ["Click-to-call + booking forms", "Service-area landing pages", "Reviews + GBP automation"]),
  mk("hvac", Zap, "HVAC", "Home Services & Trades", "Emergency-ready sites for HVAC pros.",
    "HVAC websites built for emergency calls, seasonal demand spikes, and service-area domination.",
    ["Emergency vs. install routing", "Seasonal demand", "Service-area SEO"],
    ["Click-to-call urgency design", "Seasonal campaigns", "Hyper-local SEO"]),
  mk("plumbing", Wrench, "Plumbing", "Home Services & Trades", "Click-to-call plumbing websites.",
    "Plumbing websites optimized for emergency calls, water-damage urgency, and Google Local Service Ads.",
    ["Emergency response design", "GLSA eligibility", "Service area coverage"],
    ["Urgency-first design", "GLSA + GBP optimization", "Service-area landing pages"]),
  mk("electrical", Lightbulb, "Electrical Contractors", "Home Services & Trades", "Lead-gen sites for electricians.",
    "Electrical contractor websites built for residential, commercial, and EV-charging service lines.",
    ["Multi-service-line clarity", "Permit and licensing trust", "Commercial vs. residential funnels"],
    ["Service-line architecture", "Licensing + trust signals", "Dual-audience funnels"]),
  mk("roofing", HardHat, "Roofing", "Home Services & Trades", "Storm-ready sites for roofers.",
    "Roofing websites engineered for storm-response, insurance work, and high-ticket lead capture.",
    ["Storm-response surges", "Insurance claim education", "Lead quality vs. quantity"],
    ["Storm landing pages", "Insurance content", "Qualified lead forms"]),
  mk("landscaping", TreePine, "Landscaping & Lawn Care", "Home Services & Trades", "Visual sites for landscape pros.",
    "Portfolio-rich landscaping websites with seasonal service flows and recurring-contract upsells.",
    ["Seasonal demand", "Recurring contracts", "Portfolio quality"],
    ["Seasonal campaigns", "Recurring service plans", "Visual portfolios"]),
  mk("cleaning", Sparkles, "Cleaning Services", "Home Services & Trades", "Recurring-revenue cleaning sites.",
    "Residential and commercial cleaning websites with instant quotes and recurring booking.",
    ["Instant pricing expectations", "Recurring vs. one-time", "Trust and background checks"],
    ["Instant quote calculators", "Recurring plans", "Trust signal design"]),
  mk("pest-control", ShieldCheck, "Pest Control", "Home Services & Trades", "Local-SEO-first pest control sites.",
    "Pest control websites with service plans, hyper-local SEO, and seasonal-pest landing pages.",
    ["Seasonal pest spikes", "Service plan upsells", "Local competition"],
    ["Seasonal landing pages", "Recurring plan flows", "Map-pack SEO"]),
  mk("moving", Truck, "Moving & Storage", "Home Services & Trades", "Quote-driving sites for movers.",
    "Moving company websites with instant quote forms, route-aware SEO, and review-rich social proof.",
    ["Quote form complexity", "Long vs. local routes", "Review reputation"],
    ["Smart quote forms", "Route-based SEO", "Review aggregation"]),
  mk("solar", Sprout, "Solar & Renewable Energy", "Home Services & Trades", "Lead-gen sites for solar installers.",
    "Solar installer websites with savings calculators, financing flows, and incentive-aware content.",
    ["Incentive complexity", "Long sales cycle", "High CPC competition"],
    ["Savings calculators", "Financing integrations", "Incentive content hubs"]),

  // Finance & Fintech
  mk("finance", Building2, "Financial Advisors", "Finance & Fintech", "Compliant, trustworthy sites for advisors.",
    "Compliance-ready websites for financial advisors, wealth managers, and RIAs — calm, credible, and lead-qualifying.",
    ["Compliance and disclosure review", "Trust-building above the fold", "Lead quality over volume"],
    ["Compliance-friendly CMS workflows", "Authority-led content design", "Qualified-lead intake forms"]),
  mk("fintech", CreditCard, "Fintech & Payments", "Finance & Fintech", "Conversion sites for fintech startups.",
    "High-trust fintech and payments websites — built for conversion, compliance, and enterprise sales.",
    ["Trust at first impression", "Compliance content", "Enterprise + SMB funnels"],
    ["Trust-first design system", "Compliance content hubs", "Dual ICP funnels"]),
  mk("banking", Landmark, "Community Banks & Credit Unions", "Finance & Fintech", "Member-first banking websites.",
    "Modern community bank and credit union websites with rate tables, branch finders, and ADA compliance.",
    ["ADA and regulator scrutiny", "Branch and ATM finders", "Rate freshness"],
    ["WCAG-compliant builds", "Branch finder + maps", "Automated rate updates"]),
  mk("crypto", Coins, "Crypto & Web3", "Finance & Fintech", "Modern sites for crypto and Web3 brands.",
    "Web3, crypto, and DeFi websites with wallet integrations, tokenomics pages, and credibility-first design.",
    ["Trust in a noisy market", "Wallet and chain integrations", "Fast-moving content"],
    ["Credibility-first design", "Wallet/chain integrations", "Fast publishing workflows"]),
  mk("wealth-management", PiggyBank, "Wealth Management", "Finance & Fintech", "Premium sites for wealth firms.",
    "Premium wealth management and family office websites — quiet, confident, and built for high-net-worth referrals.",
    ["Premium positioning", "Referral-driven growth", "Compliance review"],
    ["Premium design language", "Referral-friendly content", "Compliance workflows"]),

  // Manufacturing & Industrial
  mk("manufacturing", Factory, "Manufacturing", "Manufacturing & Industrial", "B2B sites with deep product content.",
    "Industrial and B2B manufacturer websites with deep product catalogs, capability content, and SEO that earns RFQs.",
    ["Complex product catalogs", "Long, multi-stakeholder sales cycles", "Thin or outdated SEO"],
    ["Catalog + spec-sheet architecture", "Capabilities-led storytelling", "Technical and category SEO"]),
  mk("industrial-supply", Boxes, "Industrial Supply & Distribution", "Manufacturing & Industrial", "Catalog-driven distributor sites.",
    "Industrial distributor websites with product catalogs, ERP integrations, and account-based buying flows.",
    ["Large product catalogs", "ERP/PIM integrations", "Account-based pricing"],
    ["Headless catalog builds", "ERP + PIM sync", "Account-aware storefronts"]),
  mk("logistics", Truck, "Logistics & Freight", "Manufacturing & Industrial", "B2B sites for 3PLs and carriers.",
    "Logistics, freight, and 3PL websites with quote tools, tracking integrations, and shipper-focused content.",
    ["Shipper trust at scale", "Quote and tracking flows", "Mode-specific content"],
    ["Trust-first design", "Quote + tracking tools", "Mode-specific landing pages"]),
  mk("warehousing", Warehouse, "Warehousing & Fulfillment", "Manufacturing & Industrial", "Lead-gen sites for 3PLs.",
    "Warehousing and fulfillment websites with capability calculators, integration showcases, and RFQ flows.",
    ["Capability transparency", "Integration depth", "RFQ qualification"],
    ["Capability pages", "Integration directory", "Qualified RFQ flows"]),
  mk("aerospace", Rocket, "Aerospace & Defense", "Manufacturing & Industrial", "Authority sites for A&D firms.",
    "Aerospace and defense websites with certification-led content, ITAR-aware messaging, and program-track records.",
    ["ITAR and certifications", "Program credibility", "Government and prime buyers"],
    ["Certification-led content", "Program case studies", "ITAR-aware workflows"]),
  mk("automotive", Car, "Automotive & Dealerships", "Manufacturing & Industrial", "Inventory-driven dealer sites.",
    "Auto dealer, repair shop, and aftermarket websites with inventory feeds, service booking, and lead capture.",
    ["Inventory feed reliability", "Service vs. sales funnels", "Local SEO"],
    ["Inventory integrations", "Dual funnels", "Local SEO + reviews"]),
  mk("energy", Fuel, "Oil, Gas & Energy", "Manufacturing & Industrial", "Enterprise sites for energy firms.",
    "Enterprise energy, oil, gas, and utility websites — built for investor, partner, and recruitment audiences.",
    ["Multi-audience structure", "Investor and ESG content", "Regulatory complexity"],
    ["Multi-audience IA", "Investor + ESG hubs", "Regulator-aware CMS"]),
  mk("agriculture", Wheat, "Agriculture & Agritech", "Manufacturing & Industrial", "B2B and DTC sites for ag.",
    "Agriculture, agritech, and farm-to-table websites — bridging dealer networks, growers, and direct consumers.",
    ["Dealer vs. grower audiences", "Seasonal content", "DTC + B2B funnels"],
    ["Multi-audience IA", "Seasonal campaigns", "Dual-funnel storefronts"]),

  // Retail & eCommerce
  mk("ecommerce", ShoppingCart, "eCommerce (General)", "Retail & eCommerce", "Shopify & WooCommerce stores built to scale.",
    "Stores designed for conversion and built for scale — from first-launch DTC brands to enterprise replatforms.",
    ["Checkout friction and abandonment", "Slow storefronts hurting SEO", "Disconnected ops and marketing stack"],
    ["Conversion-focused checkout work", "Headless or hybrid storefronts", "CRM, ESP, and ERP integrations"]),
  mk("fashion-apparel", Shirt, "Fashion & Apparel", "Retail & eCommerce", "DTC sites for fashion brands.",
    "Editorial DTC websites for fashion and apparel brands — built around storytelling, drops, and lifetime value.",
    ["Brand-first storytelling", "Drop and launch traffic spikes", "Returns and sizing friction"],
    ["Editorial design systems", "Launch-ready infrastructure", "Sizing + returns UX"]),
  mk("jewelry", Gem, "Jewelry & Luxury", "Retail & eCommerce", "Premium sites for jewelry brands.",
    "High-end jewelry and luxury goods websites — built for trust, customization, and concierge service.",
    ["Trust at high price points", "Customization flows", "Concierge service expectations"],
    ["Trust-first design", "Custom configurators", "Concierge messaging"]),
  mk("furniture-home", Bed, "Furniture & Home Goods", "Retail & eCommerce", "Visual sites for home brands.",
    "Furniture and home goods websites with room scenes, configurators, and white-glove delivery flows.",
    ["Large, image-heavy catalogs", "Configurators and SKUs", "Shipping and delivery UX"],
    ["Visual merchandising", "Configurator builds", "Shipping/delivery UX"]),
  mk("beauty-cosmetics", Sparkles, "Beauty & Cosmetics", "Retail & eCommerce", "DTC sites for beauty brands.",
    "Beauty and cosmetics DTC websites with shade finders, subscriptions, and ingredient transparency.",
    ["Shade and skin-tone UX", "Subscription LTV", "Ingredient education"],
    ["Shade finders", "Subscription flows", "Ingredient hubs"]),
  mk("food-beverage", Utensils, "Food & Beverage Brands", "Retail & eCommerce", "DTC and wholesale food sites.",
    "Food and beverage brand websites — DTC, wholesale, and retail-locator ready.",
    ["DTC vs. wholesale flows", "Retail-locator UX", "Cold-chain and compliance"],
    ["Dual-funnel storefronts", "Store locators", "Compliance-aware CMS"]),
  mk("specialty-retail", Store, "Specialty & Boutique Retail", "Retail & eCommerce", "Charming sites for boutique stores.",
    "Boutique and specialty retail websites with in-store + online sync, gift cards, and local SEO.",
    ["Online and in-store sync", "Gift card and event flows", "Local SEO"],
    ["Omnichannel integrations", "Gift + event modules", "Hyper-local SEO"]),

  // Hospitality, Travel & Food
  mk("restaurants", Pizza, "Restaurants & Cafés", "Hospitality & Travel", "Order-ready sites for restaurants.",
    "Restaurant and café websites with online ordering, reservations, and menu management built in.",
    ["Online ordering integrations", "Menu updates and pricing", "Reservation flows"],
    ["Ordering + reservation flows", "Easy menu CMS", "Local SEO + reviews"]),
  mk("hotels", Hotel, "Hotels & Resorts", "Hospitality & Travel", "Direct-booking websites for hotels.",
    "Independent hotel, resort, and boutique property websites engineered to win direct bookings over OTAs.",
    ["OTA dependency", "Direct-booking incentives", "Group and event sales"],
    ["Booking engine integration", "Direct-book offers", "Group/event landing pages"]),
  mk("travel-tours", Plane, "Travel & Tours", "Hospitality & Travel", "Booking sites for tour operators.",
    "Tour operator, travel agency, and destination websites with booking, itineraries, and inspiration content.",
    ["Booking and availability sync", "Inspiration vs. conversion", "Seasonal demand"],
    ["Booking integrations", "Inspiration hubs", "Seasonal campaigns"]),
  mk("event-venues", Mic, "Event Venues & Catering", "Hospitality & Travel", "Inquiry-driving venue websites.",
    "Wedding venue, event space, and catering websites — built around galleries, inquiries, and floor plans.",
    ["Inquiry-form qualification", "Gallery performance", "Floor plan and capacity content"],
    ["Qualified inquiry forms", "Image-optimized galleries", "Capacity + floor plan modules"]),
  mk("breweries-wineries", Wine, "Breweries, Wineries & Distilleries", "Hospitality & Travel", "Brand sites for craft beverages.",
    "Brewery, winery, and distillery websites with age-gates, club subscriptions, and tasting-room booking.",
    ["Age gating and compliance", "Club LTV", "Tasting-room booking"],
    ["Compliant age gates", "Club subscription flows", "Tasting-room booking"]),
  mk("coffee-shops", Coffee, "Coffee Shops & Roasters", "Hospitality & Travel", "Brand and DTC sites for roasters.",
    "Coffee shop and roaster websites with subscriptions, wholesale, and a strong brand voice.",
    ["Subscription LTV", "Wholesale + DTC", "Brand consistency"],
    ["Subscription flows", "Dual-funnel store", "Brand systems"]),
  mk("rideshare-transport", Train, "Transportation & Transit", "Hospitality & Travel", "Modern sites for transport brands.",
    "Transit, rideshare, charter, and last-mile transport websites with booking, tracking, and B2B flows.",
    ["Booking + tracking UX", "B2B vs. B2C", "Real-time data"],
    ["Booking + tracking", "Dual funnels", "Real-time integrations"]),

  // Education
  mk("k12-schools", School, "K-12 Schools", "Education", "Parent-friendly K-12 websites.",
    "Public, private, and charter K-12 school websites — parent-friendly, ADA-compliant, and built for enrollment.",
    ["ADA and Title IX scrutiny", "Parent communications", "Enrollment funnels"],
    ["WCAG-compliant builds", "Parent communication hubs", "Enrollment funnels"]),
  mk("higher-ed", GraduationCap, "Colleges & Universities", "Education", "Enterprise sites for higher ed.",
    "College and university websites at the program, department, or institutional level — built for recruitment and research.",
    ["Massive content surface", "Multi-stakeholder governance", "Recruitment vs. research"],
    ["Scalable design systems", "Governance-aware CMS", "Audience-specific funnels"]),
  mk("online-courses", BookOpen, "Online Courses & EdTech", "Education", "Conversion sites for course creators.",
    "Course creator, bootcamp, and EdTech websites with checkout, LMS integrations, and student lifecycle marketing.",
    ["Checkout + LMS friction", "Free vs. paid funnels", "Student LTV"],
    ["Optimized checkout", "LMS integrations", "Lifecycle email + SMS"]),
  mk("tutoring", Library, "Tutoring & Test Prep", "Education", "Lead-gen sites for tutors.",
    "Tutoring and test prep websites with parent-friendly intake, scheduling, and outcome storytelling.",
    ["Parent trust", "Scheduling complexity", "Outcome proof"],
    ["Parent-led design", "Booking + reminders", "Outcome storytelling"]),
  mk("religious", Church, "Religious Organizations", "Education", "Welcoming sites for churches & faith groups.",
    "Church, synagogue, mosque, and faith-based organization websites with sermons, giving, and community calendars.",
    ["Sermon archive UX", "Online giving", "Volunteer signup"],
    ["Sermon libraries", "Giving integrations", "Volunteer + event flows"]),

  // Nonprofits & Public Sector
  mk("nonprofits", Heart, "Nonprofits & Foundations", "Nonprofits & Public", "Donation-ready sites for missions.",
    "Mission-first websites with donation flows, volunteer signups, and storytelling that turns visitors into supporters.",
    ["Donation friction", "Volunteer + program management", "Limited internal tech capacity"],
    ["Donation + recurring giving flows", "Volunteer and program signups", "Care plans built for lean teams"]),
  mk("government", Landmark, "Government & Civic", "Nonprofits & Public", "Accessible sites for civic orgs.",
    "Local government, agency, and civic organization websites — WCAG-compliant, transparent, and citizen-friendly.",
    ["WCAG and Section 508", "Public records and transparency", "Multi-language support"],
    ["WCAG/508 builds", "Transparency hubs", "Multi-language CMS"]),
  mk("associations", HandHeart, "Associations & Member Orgs", "Nonprofits & Public", "Member-portal-ready sites.",
    "Trade association, chamber, and member organization websites with directories, events, and member portals.",
    ["Member portal complexity", "Event registration", "Directory management"],
    ["AMS integrations", "Event registration", "Searchable directories"]),
  mk("advocacy", Globe, "Advocacy & Political", "Nonprofits & Public", "Mobilization sites for campaigns.",
    "Advocacy, PAC, and political campaign websites — built for fundraising, volunteer mobilization, and rapid response.",
    ["Fundraising spikes", "Volunteer mobilization", "Rapid content publishing"],
    ["Scalable donation infra", "Volunteer + action flows", "Fast publishing workflows"]),

  // Technology & SaaS
  mk("saas", Cloud, "SaaS & B2B Software", "Technology & SaaS", "Conversion sites for SaaS.",
    "SaaS marketing websites and product-led growth funnels — built to lift activation, expansion, and pipeline.",
    ["Activation drop-off", "Self-serve vs. sales-led", "Programmatic SEO"],
    ["PLG funnel design", "Dual-motion architecture", "Programmatic SEO builds"]),
  mk("it-services", Server, "IT Services & MSPs", "Technology & SaaS", "Lead-gen sites for MSPs.",
    "Managed services and IT consultancy websites with verticalized content, case studies, and partner ecosystems.",
    ["Generic positioning", "Long enterprise cycles", "Partner co-marketing"],
    ["Vertical positioning", "Case studies that sell", "Partner microsites"]),
  mk("cybersecurity", ShieldCheck, "Cybersecurity", "Technology & SaaS", "Authority sites for security firms.",
    "Cybersecurity vendor and consultancy websites with credibility-first design and demand generation built in.",
    ["Trust above the fold", "Buyer education", "Compliance content"],
    ["Trust-first design", "Education-led content", "Compliance hubs"]),
  mk("ai-ml", Cpu, "AI & Machine Learning", "Technology & SaaS", "Modern sites for AI products.",
    "AI, ML, and data product websites — built to convert technical buyers without alienating business stakeholders.",
    ["Dual-audience messaging", "Hype vs. proof", "Fast-moving roadmaps"],
    ["Dual-audience IA", "Proof-led case studies", "Fast publishing workflows"]),
  mk("data-analytics", Database, "Data & Analytics", "Technology & SaaS", "B2B sites for data platforms.",
    "Data, analytics, and BI platform websites — built around integrations, ROI proof, and technical depth.",
    ["Integration depth", "ROI proof", "Buyer + user audiences"],
    ["Integration directories", "ROI calculators", "Dual-audience IA"]),
  mk("dev-tools", Code, "Developer Tools", "Technology & SaaS", "Docs-rich sites for dev tools.",
    "Developer tool and infrastructure websites — clean, fast, and built around docs, examples, and a credible community.",
    ["Docs and DX", "Community signals", "Pricing transparency"],
    ["Docs-integrated marketing", "Community modules", "Transparent pricing"]),
  mk("mobile-apps", Smartphone, "Mobile Apps", "Technology & SaaS", "Install-driving sites for apps.",
    "Mobile app marketing websites with deep links, app-store optimization tie-ins, and lifecycle marketing.",
    ["App store vs. web funnel", "Deep linking", "Retention messaging"],
    ["Deep link architecture", "App-store-aware design", "Retention content"]),
  mk("telecom", Satellite, "Telecom & ISPs", "Technology & SaaS", "Subscriber-driving telecom sites.",
    "Telecom, ISP, and connectivity provider websites with coverage maps, plan comparison, and account portals.",
    ["Coverage and address checks", "Plan comparison UX", "Self-service portals"],
    ["Coverage map UX", "Plan comparison tools", "Portal integrations"]),

  // Media, Arts & Entertainment
  mk("media-publishing", Newspaper, "Media & Publishing", "Media & Entertainment", "Speed-first publisher sites.",
    "Publisher, magazine, and news websites engineered for core web vitals, ad yield, and subscriptions.",
    ["Core web vitals at scale", "Ad yield vs. UX", "Subscription paywalls"],
    ["Performance-first builds", "Yield-aware ad UX", "Paywall integrations"]),
  mk("entertainment", Film, "Film, TV & Entertainment", "Media & Entertainment", "Cinematic sites for entertainment.",
    "Production company, studio, and entertainment brand websites — cinematic, fast, and built around release moments.",
    ["Cinematic media performance", "Release moment spikes", "Talent and project IA"],
    ["Optimized media pipelines", "Release campaign infra", "Talent + project modules"]),
  mk("music", Music, "Music & Record Labels", "Media & Entertainment", "Artist and label websites.",
    "Artist, band, and record label websites with tour dates, merch, and streaming integrations.",
    ["Tour + merch + streaming sync", "Drop moments", "Fan email capture"],
    ["Tour/merch integrations", "Drop campaigns", "Fan list growth"]),
  mk("photography", Camera, "Photography & Videography", "Media & Entertainment", "Portfolio sites for photographers.",
    "Photography and videography portfolio websites — built around galleries, inquiries, and booking.",
    ["Heavy gallery performance", "Inquiry qualification", "Booking flows"],
    ["Optimized galleries", "Qualified inquiry forms", "Booking integrations"]),
  mk("creative-arts", Palette, "Creative Arts & Studios", "Media & Entertainment", "Portfolios for creative studios.",
    "Creative studio, design agency, and illustrator websites — built to attract dream clients and showcase craft.",
    ["Craft-led storytelling", "Inquiry quality", "Project case studies"],
    ["Craft-forward design", "Qualified inquiries", "Custom case studies"]),
  mk("gaming", Gamepad2, "Gaming & Esports", "Media & Entertainment", "Community sites for gaming brands.",
    "Game studio, publisher, and esports organization websites with launch infrastructure, community hubs, and merch.",
    ["Launch traffic spikes", "Community engagement", "Merch + sponsorship"],
    ["Launch-ready infra", "Community modules", "Merch + sponsorship pages"]),
  mk("broadcasting", Radio, "Broadcasting & Podcasts", "Media & Entertainment", "Audio-first websites.",
    "Radio, podcast, and broadcasting websites with episode archives, ad placements, and sponsor packages.",
    ["Episode archive UX", "Ad and sponsor inventory", "Listener growth"],
    ["Episode-first IA", "Sponsor inventory pages", "Listener growth tools"]),
  mk("streaming", Tv, "Streaming & OTT", "Media & Entertainment", "Subscriber sites for streamers.",
    "Streaming and OTT platform marketing sites with subscription funnels, content discovery, and device support pages.",
    ["Subscription funnel CRO", "Content discovery", "Device support content"],
    ["CRO-tuned signup flows", "Discovery-led design", "Device + help hubs"]),

  // Lifestyle & Local
  mk("weddings", Heart, "Weddings & Events", "Lifestyle & Local", "Inquiry sites for wedding pros.",
    "Wedding planner, florist, and event vendor websites — visual, inquiry-rich, and built for the dream-client funnel.",
    ["Inquiry overwhelm", "Image performance", "Seasonal demand"],
    ["Qualified inquiry forms", "Optimized galleries", "Seasonal campaigns"]),
  mk("pets", Dog, "Pet Services", "Lifestyle & Local", "Booking sites for pet pros.",
    "Pet grooming, boarding, training, and daycare websites with booking, packages, and owner education.",
    ["Booking + package complexity", "Owner trust", "Local SEO"],
    ["Booking + package flows", "Trust-first design", "Hyper-local SEO"]),
  mk("childcare", Baby, "Childcare & Daycare", "Lifestyle & Local", "Parent-trust childcare sites.",
    "Daycare, preschool, and childcare websites — built around parent trust, enrollment, and parent communication.",
    ["Parent trust", "Enrollment funnel", "Daily communication"],
    ["Trust-first design", "Enrollment funnels", "Parent comms modules"]),
  mk("salons-barbershops", Scissors, "Salons & Barbershops", "Lifestyle & Local", "Booking-first salon sites.",
    "Salon and barbershop websites with online booking, stylist pages, and reviews-first social proof.",
    ["Stylist-level booking", "Walk-in vs. appointment", "Reviews and Instagram"],
    ["Stylist booking UX", "Booking + walk-in flows", "Review + IG modules"]),
  mk("outdoor-recreation", Mountain, "Outdoor & Adventure", "Lifestyle & Local", "Booking sites for adventure brands.",
    "Outdoor outfitter, guide, and adventure travel websites with trip booking, gear shops, and inspiration content.",
    ["Booking + gear funnels", "Seasonal demand", "Inspiration vs. conversion"],
    ["Dual-funnel storefronts", "Seasonal campaigns", "Inspiration hubs"]),
  mk("auto-services", Car, "Auto Repair & Services", "Lifestyle & Local", "Booking sites for auto shops.",
    "Auto repair, detailing, and tire shop websites with online booking, estimates, and review-driven local SEO.",
    ["Online estimate UX", "Booking + walk-in", "Local SEO"],
    ["Booking + estimate forms", "Walk-in + appointment", "Hyper-local SEO"]),
  mk("marine", Sailboat, "Marine & Boating", "Lifestyle & Local", "Sites for marinas and boat brands.",
    "Marina, boat dealer, and marine service websites with inventory, slip booking, and seasonal flows.",
    ["Inventory + slip booking", "Seasonal demand", "Local SEO"],
    ["Inventory + booking", "Seasonal campaigns", "Local SEO"]),
  mk("cannabis", Leaf, "Cannabis & CBD", "Lifestyle & Local", "Compliance-aware cannabis sites.",
    "Dispensary, cannabis brand, and CBD eCommerce websites — built around state-level compliance and conversion.",
    ["State-by-state compliance", "Age gates", "Payment + shipping limits"],
    ["Compliance-aware CMS", "Age gates", "Compliant checkout flows"]),
];

export const INDUSTRY_CATEGORIES: string[] = Array.from(
  new Set(INDUSTRIES.map((i) => i.category))
);
