/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as KeywordRouteImport } from './routes/$keyword'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as KeywordIndexRouteImport } from './routes/$keyword.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ResourcesWebsiteMaintenanceChecklistRouteImport } from './routes/resources.website-maintenance-checklist'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as KeywordCityRouteImport } from './routes/$keyword.$city'
import { Route as ServicesSlugIndexRouteImport } from './routes/services.$slug.index'
import { Route as ServicesSlugChildRouteImport } from './routes/services.$slug.$child'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordRoute = KeywordRouteImport.update({
  id: '/$keyword',
  path: '/$keyword',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordIndexRoute = KeywordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KeywordRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesWebsiteMaintenanceChecklistRoute =
  ResourcesWebsiteMaintenanceChecklistRouteImport.update({
    id: '/website-maintenance-checklist',
    path: '/website-maintenance-checklist',
    getParentRoute: () => ResourcesRoute,
  } as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordCityRoute = KeywordCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => KeywordRoute,
} as any)
const ServicesSlugIndexRoute = ServicesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesSlugRoute,
} as any)
const ServicesSlugChildRoute = ServicesSlugChildRouteImport.update({
  id: '/$child',
  path: '/$child',
  getParentRoute: () => ServicesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$keyword': typeof KeywordRouteWithChildren
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$keyword/$city': typeof KeywordCityRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/resources/website-maintenance-checklist': typeof ResourcesWebsiteMaintenanceChecklistRoute
  '/services/$slug': typeof ServicesSlugRouteWithChildren
  '/$keyword/': typeof KeywordIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$slug/$child': typeof ServicesSlugChildRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$keyword/$city': typeof KeywordCityRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/resources/website-maintenance-checklist': typeof ResourcesWebsiteMaintenanceChecklistRoute
  '/$keyword': typeof KeywordIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/$slug/$child': typeof ServicesSlugChildRoute
  '/services/$slug': typeof ServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$keyword': typeof KeywordRouteWithChildren
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$keyword/$city': typeof KeywordCityRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/resources/website-maintenance-checklist': typeof ResourcesWebsiteMaintenanceChecklistRoute
  '/services/$slug': typeof ServicesSlugRouteWithChildren
  '/$keyword/': typeof KeywordIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$slug/$child': typeof ServicesSlugChildRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$keyword'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/$keyword/$city'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/resources/website-maintenance-checklist'
    | '/services/$slug'
    | '/$keyword/'
    | '/industries/'
    | '/locations/'
    | '/services/'
    | '/services/$slug/$child'
    | '/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/$keyword/$city'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/resources/website-maintenance-checklist'
    | '/$keyword'
    | '/industries'
    | '/locations'
    | '/services'
    | '/services/$slug/$child'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/$keyword'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/$keyword/$city'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/resources/website-maintenance-checklist'
    | '/services/$slug'
    | '/$keyword/'
    | '/industries/'
    | '/locations/'
    | '/services/'
    | '/services/$slug/$child'
    | '/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeywordRoute: typeof KeywordRouteWithChildren
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRouteWithChildren
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$keyword': {
      id: '/$keyword'
      path: '/$keyword'
      fullPath: '/$keyword'
      preLoaderRoute: typeof KeywordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$keyword/': {
      id: '/$keyword/'
      path: '/'
      fullPath: '/$keyword/'
      preLoaderRoute: typeof KeywordIndexRouteImport
      parentRoute: typeof KeywordRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/website-maintenance-checklist': {
      id: '/resources/website-maintenance-checklist'
      path: '/website-maintenance-checklist'
      fullPath: '/resources/website-maintenance-checklist'
      preLoaderRoute: typeof ResourcesWebsiteMaintenanceChecklistRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$keyword/$city': {
      id: '/$keyword/$city'
      path: '/$city'
      fullPath: '/$keyword/$city'
      preLoaderRoute: typeof KeywordCityRouteImport
      parentRoute: typeof KeywordRoute
    }
    '/services/$slug/': {
      id: '/services/$slug/'
      path: '/'
      fullPath: '/services/$slug/'
      preLoaderRoute: typeof ServicesSlugIndexRouteImport
      parentRoute: typeof ServicesSlugRoute
    }
    '/services/$slug/$child': {
      id: '/services/$slug/$child'
      path: '/$child'
      fullPath: '/services/$slug/$child'
      preLoaderRoute: typeof ServicesSlugChildRouteImport
      parentRoute: typeof ServicesSlugRoute
    }
  }
}

interface KeywordRouteChildren {
  KeywordCityRoute: typeof KeywordCityRoute
  KeywordIndexRoute: typeof KeywordIndexRoute
}

const KeywordRouteChildren: KeywordRouteChildren = {
  KeywordCityRoute: KeywordCityRoute,
  KeywordIndexRoute: KeywordIndexRoute,
}

const KeywordRouteWithChildren =
  KeywordRoute._addFileChildren(KeywordRouteChildren)

interface ResourcesRouteChildren {
  ResourcesWebsiteMaintenanceChecklistRoute: typeof ResourcesWebsiteMaintenanceChecklistRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesWebsiteMaintenanceChecklistRoute:
    ResourcesWebsiteMaintenanceChecklistRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ServicesSlugRouteChildren {
  ServicesSlugChildRoute: typeof ServicesSlugChildRoute
  ServicesSlugIndexRoute: typeof ServicesSlugIndexRoute
}

const ServicesSlugRouteChildren: ServicesSlugRouteChildren = {
  ServicesSlugChildRoute: ServicesSlugChildRoute,
  ServicesSlugIndexRoute: ServicesSlugIndexRoute,
}

const ServicesSlugRouteWithChildren = ServicesSlugRoute._addFileChildren(
  ServicesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeywordRoute: KeywordRouteWithChildren,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  ServicesSlugRoute: ServicesSlugRouteWithChildren,
  IndustriesIndexRoute: IndustriesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
